# Connectors module
from .base import BaseConnector
from .cnpq import CNPqConnector
from .openalex import OpenAlexConnector
from .comex import ComexStatConnector
from .ibge import IBGEConnector
from .capes import CAPESConnector
from .scholarships import InternationalScholarshipsConnector
from .inep import INEPConnector
from .github import GitHubConnector
from .ipeadata import IPEADataConnector
from .brasilapi import BrasilAPIConnector
from .pncp import PNCPConnector
from .querido_diario import QueridoDiarioConnector
from .aneel import ANEELConnector
from .anp import ANPConnector
from .dados_gov import DadosGovConnector
from .dou import DOUConnector
from .transparencia import TransparenciaConnector
from .siconfi import SICONFIConnector
from .bcb import BCBConnector
from .anvisa import ANVISAConnector
from .anatel import ANATELConnector
from .cvm import CVMConnector
from .ibama import IBAMAConnector
from .inpe import INPEConnector
from .fnde import FNDEConnector
from .tcu import TCUConnector
from .rais_caged import RAISCAGEDConnector
