INSERT INTO public.build_log (data, categoria, titulo, descricao, fonte, dificuldade, resolucao, eh_achado_pesquisa, nota_desenvolvimento, anexo_texto)
VALUES (
'2026-09-11',
'obstaculo_institucional',
'Auditoria de segurança externa — 4 tabelas com RLS permitindo escrita a qualquer conta autenticada',
'Relatório de auditoria de segurança independente identificou 5 achados (0 crítico, 2 alta, 2 média, 1 baixa) no repositório motor4pufpr (commit 6d15d22, 883 commits de histórico auditados). Achado raiz: quatro tabelas criadas após a implementação de community_feedback/is_admin() (build_log, science_specialization_index, regional_institutes, city_geocode) voltaram ao padrão USING(true)/WITH CHECK(true) para o papel authenticated, permitindo que qualquer conta logada apague ou reescreva o Diário de Construção inteiro, os índices de especialização científica exibidos publicamente, o diretório de concentradores regionais e o cache de geocodificação. Achado derivado: fonte_url de science_specialization_index chega sem validação de esquema a um href, permitindo injeção de link malicioso disfarçado de fonte oficial CGEE/MCTI. Pontos fortes confirmados na mesma auditoria: RLS por dono corretamente implementado em todas as tabelas de pesquisa do autor (research_authors/themes/articles/documents/highlights), bucket privado research-docs, moderação de community_feedback já protegida por is_admin(), zero segredos expostos em 883 commits de histórico git, backend FastAPI falha fechado sem chave, e edge functions de IA com rate limit e allowlist de payload.',
'Relatório de Auditoria de Segurança independente (PDF anexado), 2026-09-11',
'As 4 tabelas afetadas foram criadas em sessões diferentes ao longo do desenvolvimento sem reaproveitar o padrão de policy já estabelecido em community_feedback — nenhuma delas tinha coluna de dono nem verificação de papel.',
'Migração corretiva aplicada trocando as policies de escrita para public.is_admin() nas três tabelas relevantes e revogando escrita de authenticated em city_geocode (só service_role/bulk-ingest); validação de esquema https adicionada ao fonte_url antes de href; canEdit do frontend passou a usar supabase.rpc(''is_admin'') em vez de !!user.',
true,
'Achado metodologicamente relevante: o padrão de segurança estabelecido (is_admin()) não foi automaticamente propagado para tabelas criadas depois, apesar de o padrão já existir no código-base — evidência de como boas práticas de segurança se degradam silenciosamente ao longo de um desenvolvimento iterativo assistido por IA sem checklist de conformidade entre migrações. Desenvolver como reflexão metodológica sobre auditabilidade contínua (não pontual) como requisito para artefatos de pesquisa que evoluem por adição incremental de funcionalidades — relevante para o capítulo sobre reprodutibilidade e confiabilidade do artefato computacional na tese.',
'RELATÓRIO DE AUDITORIA DE SEGURANÇA — motor4pufpr (commit 6d15d22; 883 commits de histórico auditados), 2026-09-11.

RESUMO EXECUTIVO: 5 achados — 0 crítico, 2 alta, 2 média, 1 baixa. Nenhum segredo exposto no histórico git. RLS por dono corretamente implementado nas tabelas de pesquisa do autor (research_authors, research_themes, research_articles, research_documents, research_highlights). Bucket research-docs privado. Moderação de community_feedback já protegida por public.is_admin(). Backend FastAPI falha fechado quando a chave não está configurada. Edge functions de IA com rate limit e allowlist de payload.

ISSUE 1 (ALTA) — Policies de escrita liberadas para qualquer conta autenticada. Quatro tabelas criadas após a implementação de community_feedback/is_admin() voltaram ao padrão USING(true)/WITH CHECK(true) para o papel authenticated: build_log (Diário de Construção), science_specialization_index (índices de especialização científica exibidos publicamente), regional_institutes (diretório de concentradores regionais) e city_geocode (cache de geocodificação). Impacto: qualquer conta logada pode apagar ou reescrever integralmente esses conjuntos de dados, incluindo o registro metodológico da tese. Nenhuma das tabelas possui coluna de dono nem verificação de papel. Correção recomendada: substituir as policies de escrita por public.is_admin() em build_log, science_specialization_index e regional_institutes; em city_geocode, remover a escrita de authenticated e mantê-la apenas em service_role (bulk-ingest). Validação: pg_policies não deve apresentar policy de escrita com qual/with_check igual a true puro para authenticated nessas tabelas.

ISSUE 2 (ALTA/MÉDIA) — fonte_url sem validação de esquema chegando a href. O campo fonte_url de science_specialization_index é repassado sem validação de esquema pela função que monta especializacao_cientifica_brasil (supabase/functions/motor-search/index.ts) e renderizado diretamente em href no componente EspecializacaoCientificaCard. Combinado com a Issue 1, permite que um link malicioso (por exemplo com esquema javascript:) seja injetado no banco e exibido ao público disfarçado de fonte oficial CGEE/MCTI. Correção recomendada: validar o esquema (apenas http/https) na origem e também antes da renderização, aplicando o mesmo helper em qualquer href alimentado por dado de banco ou API (StartupsTemaCard, PanoramaEstadualTab, PoliciesTab, OpportunityCard).

OBSERVAÇÃO OPERACIONAL (fora do repositório): verificar manualmente no painel de autenticação se a criação de contas por e-mail (Enable email signups) está desativada — não é corrigível por código.

Nota de registro: o texto acima consolida o conteúdo do relatório conforme recebido nesta sessão (resumo executivo até a Issue 2); o PDF original não foi transcrito literalmente por não estar acessível ao sistema.'
);