"""
Bases públicas integradas ao Motor4PUFPR
Atualize este arquivo sempre que uma nova base for integrada!
"""
INTEGRATED_PUBLIC_BASES = [
    # === Bases Originais ===
    {
        "id": "cnpq",
        "name": "CNPq",
        "description": "Diretório de Grupos de Pesquisa",
        "icon": "database",
        "url": "http://dgp.cnpq.br/",
        "dimension": "científica",
    },
    {
        "id": "inpi",
        "name": "INPI",
        "description": "Patentes e classificação IPC/CPC",
        "icon": "file",
        "url": "https://busca.inpi.gov.br/",
        "dimension": "tecnológica",
    },
    {
        "id": "finep",
        "name": "Finep",
        "description": "Instrumentos e chamadas públicas",
        "icon": "government",
        "url": "https://www.finep.gov.br/",
        "dimension": "institucional",
    },
    {
        "id": "ibge",
        "name": "IBGE/SIDRA",
        "description": "Produção industrial, mercado de trabalho, indicadores econômicos",
        "icon": "chart",
        "url": "https://sidra.ibge.gov.br/",
        "dimension": "produtiva",
    },
    {
        "id": "capes",
        "name": "CAPES",
        "description": "Bolsas e programas de pós-graduação",
        "icon": "scholarship",
        "url": "https://dadosabertos.capes.gov.br/",
        "dimension": "científica",
    },
    # === Novas Bases Integradas ===
    {
        "id": "openalex",
        "name": "OpenAlex",
        "description": "Artigos científicos, autores e instituições globais",
        "icon": "database",
        "url": "https://openalex.org/",
        "dimension": "científica",
    },
    {
        "id": "comexstat",
        "name": "ComexStat",
        "description": "Exportações e importações por NCM",
        "icon": "chart",
        "url": "https://comexstat.mdic.gov.br/",
        "dimension": "produtiva",
    },
    {
        "id": "ipeadata",
        "name": "IPEAData",
        "description": "Séries históricas de indicadores socioeconômicos",
        "icon": "chart",
        "url": "http://www.ipeadata.gov.br/",
        "dimension": "produtiva",
    },
    {
        "id": "brasilapi_cnpj",
        "name": "CNPJ/Receita",
        "description": "Dados cadastrais de empresas por CNAE, porte e região",
        "icon": "building",
        "url": "https://brasilapi.com.br/",
        "dimension": "produtiva",
    },
    {
        "id": "pncp",
        "name": "ComprasNet/PNCP",
        "description": "Licitações e contratações públicas federais",
        "icon": "government",
        "url": "https://pncp.gov.br/",
        "dimension": "institucional",
    },
    {
        "id": "querido_diario",
        "name": "Querido Diário",
        "description": "Diários oficiais municipais — editais e chamadas locais",
        "icon": "file",
        "url": "https://queridodiario.ok.org.br/",
        "dimension": "institucional",
    },
    {
        "id": "dou",
        "name": "DOU",
        "description": "Diário Oficial da União — portarias, editais e chamadas federais",
        "icon": "file",
        "url": "https://www.in.gov.br/",
        "dimension": "institucional",
    },
    {
        "id": "aneel",
        "name": "ANEEL",
        "description": "Geração distribuída, P&D regulado no setor elétrico",
        "icon": "energy",
        "url": "https://dadosabertos.aneel.gov.br/",
        "dimension": "produtiva",
    },
    {
        "id": "anp",
        "name": "ANP",
        "description": "Petróleo, gás, biocombustíveis e P&D obrigatório",
        "icon": "energy",
        "url": "https://dados.gov.br/",
        "dimension": "produtiva",
    },
    {
        "id": "dados_gov",
        "name": "Portal Dados Abertos",
        "description": "Catálogo central de datasets do governo federal",
        "icon": "database",
        "url": "https://dados.gov.br/",
        "dimension": "institucional",
    },
    {
        "id": "transparencia",
        "name": "Portal da Transparência",
        "description": "Convênios, despesas, sanções (CEIS/CNEP/CEPIM)",
        "icon": "government",
        "url": "https://portaldatransparencia.gov.br/",
        "dimension": "institucional",
    },
    {
        "id": "siconfi",
        "name": "Tesouro/SICONFI",
        "description": "Finanças públicas de estados e municípios",
        "icon": "chart",
        "url": "https://siconfi.tesouro.gov.br/",
        "dimension": "institucional",
    },
    {
        "id": "github",
        "name": "GitHub",
        "description": "Projetos open source e repositórios de código",
        "icon": "database",
        "url": "https://github.com/",
        "dimension": "tecnológica",
    },
    {
        "id": "inep",
        "name": "INEP",
        "description": "Censo Escolar, ENEM, ENADE — instituições e cursos",
        "icon": "scholarship",
        "url": "http://portal.inep.gov.br/",
        "dimension": "científica",
    },
]
